### ISSUE TITLE
Uncaught subprocess.CalledProcessError: Command '['explorer', 'C:\\Users\\Lucio De Benedictis\\Downloads\\GIS']' returned non-zero exit status 1.


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [hotosm/qgis-templates-and-symbology-plugin#36]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\qgis_templates_symbology\gui\qgis_templates_symbology_main.py", line 170, in open_download_folder
    result = open_folder(
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\qgis_templates_symbology\utils.py", line 100, in open_folder
    subprocess.check_call(['explorer', path])
  File "C:\OSGeo4W\apps\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['explorer', 'C:\\Users\\Lucio De Benedictis\\Downloads\\GIS']' returned non-zero exit status 1.

```
qgis_templates_symbology 1.0.1, QGIS 3.28.4-Firenze on Windows 10

**Comment by Samweli** [comment]
Hi @UrbanPlan-LDB thanks for reporting this issue, it has fixed by https://github.com/hotosm/qgis-templates-and-symbology-plugin/commit/385804abe8480404ce0e3a86ebc4458508e0b127 and the fix is available on the latest release here https://github.com/hotosm/qgis-templates-and-symbology-plugin/releases/tag/v1.0.2.

**Comment by Samweli** [comment]
@UrbanPlan-LDB closing this, you can reopen if you still have the issue, thanks.
